/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    Overwrite: typeof import('./src/components/WTF/Overwrite/Overwrite.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Segmented: typeof import('./src/components/Segmented.vue')['default']
    Synchronize: typeof import('./src/components/WTF/Synchronize/Synchronize.vue')['default']
    WTFForm: typeof import('./src/components/WTF/Overwrite/WTFForm.vue')['default']
  }
}
