/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppHeader: typeof import('./src/components/Layout/AppHeader.vue')['default']
    AppMain: typeof import('./src/components/Layout/AppMain.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Overwrite: typeof import('./src/components/WTF/Overwrite/Overwrite.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Segmented: typeof import('./src/components/Segmented.vue')['default']
    WTFForm: typeof import('./src/components/WTF/Overwrite/WTFForm.vue')['default']
  }
}
